server:
  port: 8081

spring:
  application:
    name: movie
  datasource:
    password: password
    url: jdbc:mysql://localhost:3306/movie
    username: pabloagustin
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false
